# Generated by Django 5.2.8 on 2025-11-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_level_alter_user_photo_alter_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
