# Generated by Django 5.2.8 on 2025-12-01 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_level_alter_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.CreateModel(
            name='SportLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, editable=False, max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Рейтинг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
