# Generated by Django 5.2.8 on 2025-12-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_level_remove_user_rating_sportlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportlevel',
            name='sport_type',
            field=models.CharField(choices=[('beach_volleyball', 'Пляжный волейбол'), ('beach_tennis', 'Пляжный теннис'), ('beach_badminton', 'Пляжный бадминтон')], max_length=30),
        ),
    ]
