# Generated by Django 6.0.1 on 2026-02-12 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0003_remove_participant_result'),
        ('tournaments', '0009_remove_game_round_remove_game_teams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamNumber', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.match')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_compositions_as_player1', to='participants.participant')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_compositions_as_player2', to='participants.participant')),
            ],
        ),
    ]
