# Generated by Django 5.2.8 on 2025-11-10 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('format', models.CharField(choices=[('solo', 'Одиночный'), ('pair', 'Парный')], max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('level', models.CharField(max_length=20)),
                ('players_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Активный'), ('cancelled', 'Отменён'), ('finished', 'Завершён')], default='active', max_length=10)),
                ('sport_type', models.CharField(blank=True, max_length=100)),
                ('tg_message_id', models.CharField(blank=True, max_length=32, null=True)),
                ('tg_chat_id', models.CharField(blank=True, max_length=32, null=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
