# Generated by Django 5.2.8 on 2025-11-10 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('tournaments', '0002_user_remove_tournament_organizer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tg_chat_id',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tg_message_id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('cancelled', 'Отменён'), ('finished', 'Завершён')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('solo', 'Одиночный'), ('pair', 'Парный')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='tournaments_participated', through='participants.Participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
