# Generated by Django 5.2.8 on 2025-11-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_tournament_tg_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tg_message_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
