# Generated by Django 5.2.8 on 2025-11-11 15:12

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_tg_chat_id_tournament_tg_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default=[], max_length=19, verbose_name='Допустимые уровни'),
        ),
    ]
