# Generated by Django 5.2.8 on 2025-11-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournament_sport_type_tournamentparticipant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentParticipant',
        ),
    ]
